version: '3'

volumes: 
  mariadb_data:
    driver: local

networks:
  backend:
    driver: bridge

services:

  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    container_name: wordpress  
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
    networks:
      - backend
    ports:
      - '8081:80'

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
    volumes:
      - /sessions
      - ${PWD}/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - backend
    ports:
      - '8080:80'

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - '3306:3306'

